/** Cấu kiện không gán mesh (giống convert_ifc.py). */
export const SPATIAL_CLASSES = new Set([
  'IFCOPENINGELEMENT',
  'IFCSITE',
  'IFCBUILDING',
  'IFCBUILDINGSTOREY',
  'IFCSPACE',
  'IFCGRID',
  'IFCANNOTATION',
])

export const DEFAULT_COLOR = [0.72, 0.74, 0.76]

export const AMBIGUOUS_FLOW_CLASSES = new Set([
  'IFCFLOWSEGMENT',
  'IFCFLOWFITTING',
  'IFCFLOWTERMINAL',
  'IFCFLOWCONTROLLER',
  'IFCFLOWMOVINGDEVICE',
  'IFCFLOWSTORAGEDEVICE',
  'IFCFLOWTREATMENTDEVICE',
  'IFCENERGYCONVERSIONDEVICE',
  'IFCDISTRIBUTIONELEMENT',
  'IFCDISTRIBUTIONFLOWELEMENT',
  'IFCDISTRIBUTIONCONTROLELEMENT',
  'IFCBUILDINGELEMENTPROXY',
])
